version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      codemirror:
        patterns:
          - "codemirror"
          - "@codemirror/*"
    labels:
      - "dependencies"
